# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MPP-Template' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MPP-Template
  pod 'Swinject', '~> 2.5.0'
  pod 'SwinjectStoryboard', '~> 2.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'TagListView-ObjC', '~> 0.1.1'


end
